homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Tracker

http:
  server_port: !secret tracker_server_port

frontend:

device_tracker: !include_dir_list device_trackers
zone: !include_dir_list zones
proximity: !include_dir_named proximities
