homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Trackers
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.20.0.0/16
        - 10.0.12.0/23
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

http:
  base_url: https://trackers.automation.home.prettybaked.com

frontend:

config:

view_event: !include view_event.yaml

zone: !include_dir_list zones
person:

mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
