homeassistant:
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: imperial
  time_zone: !secret home_timezone
  name: Tracker
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 172.19.0.0/16
        - 10.0.12.0/24
        - 10.0.11.174/32
      allow_bypass_login: true
    - type: homeassistant

http:
  base_url: http://trackers.constructorfleet.iot
#  server_port: !secret tracker_server_public_port

frontend:

config:

# view_event:
#   name: tracker
#   components:
#     - automatic
#     - icloud
#     - device_tracker
#     - zone

device_tracker: !include_dir_list device_trackers
zone: !include_dir_list zones
proximity: !include_dir_named proximities
sensor: !include_dir_list sensors

unifi:
  controllers: !include_dir_list unifi_controllers

mqtt: !include mqtt.yaml
mqtteventstream: !include eventstream.yaml
#mqtt_remoteinstance: !include mqtt_remoteinstance.yaml
